### ISSUE TITLE
请问能兼容到浏览器版本到那里么？

### ISSUE THREAD

**Issue by penxian** [tangbc/sugar#4]
RT IE8能支持么。

**Comment by tangbc** [comment]
不支持 IE8，虽然它支持 `Object.defineProperty` 方法，但只能在 DOM 对象上使用，所以数据绑定无法实现，IE9 及其他浏览器应该是没问题的，不过没在 IE9 上全面测试过。

**Comment by tangbc** [comment]
涉及到兼容性的几点：
* Ajax：`XMLHttpRequest`
* DOM 监听事件: `addEventListener`
* DOM 操作：`node.textContent` `node.querySelector`
* 几个 ES5 特性：`Object.create` `Object. defineProperty ` `Function.prototype.bind`
